    Numpy in python

In [1]:
import numpy as np


In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
     # use of tuples
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import numpy as np

# dimension in arrays - 1,2,3

arr = np.array(10)
print(arr)
print(type(arr))
print(arr.ndim)



10
<class 'numpy.ndarray'>
0


In [11]:
# 1 d arrays
import numpy as np
arr = np.array([10,20,30])
print(arr)
print(type(arr))
print(arr.ndim)#check where the dimenction is (1d,2d,,3d)


[10 20 30]
<class 'numpy.ndarray'>
1


In [4]:
# 2 d arrays
import numpy as np

arr = np.array([[10,20,30],[40,50,60]])
print(arr)
print(type(arr))
print(arr.ndim)#check where the dimenction is (1d,2d,,3d)

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2


In [6]:
# 3 d arrays

arr = np.array([[[10,20,30.2],[40,50,60],[70,80,90]]])
print(arr)
print(type(arr))

print(arr.ndim)  #check where the dimenction is (1d,2d,,3d)

[[[10.  20.  30.2]
  [40.  50.  60. ]
  [70.  80.  90. ]]]
<class 'numpy.ndarray'>
3


In [3]:
# 5 dimension 
import numpy as np
arr = np.array([1,2,3,4] , ndmin = 5)
print(arr)
print("the numbers of dim is :" , arr.ndim)

[[[[[1 2 3 4]]]]]
the numbers of dim is : 5


In [4]:
#  Numpy inxeding 

# Array indexing is the same as accessing an array element
# you can access an array element by referring to its index

# get first element



In [5]:
arr = np.array([2,1,3,4,56])
print(arr[0])

2


In [7]:
arr = np.array([1,2,3,4,56,5,6,7,8,9,10,20,23,25,99,69])
print(arr[0])
print(len(arr))
print("the second element is :" , arr[2])
print("the six element is :", arr[5])
print("the eight element is :", arr[7])
print("the sum of the element is :", arr[2]+arr[5]+arr[7])

1
16
the second element is : 3
the six element is : 5
the eight element is : 7
the sum of the element is : 15


In [9]:
    # access 2-D arrays for indexing
            #      0             1        this is the  index position
            #    0,  1, 2   0,  1, 2      this is the  the element inside the index element 
arr = np.array([[10,20,30],[40,50,60]])
print('2 element on 1 row is :'  , arr[0,1]) 
 # arr[0,1] where 0 is (first breaket) and in first it has 10,20,30 and in it we print 1 row means 20 (index)
  
               


2 element on 1 row is : 20


In [15]:
arr = np.array([[1,2,3,4,],[56,5,6,7]])
print('2 element on 1 row is :'  , arr[1,2]) 

2 element on 1 row is : 6


In [27]:
arr = np.array([[1,2,3,4,],[56,5,6,7]])
print('2 element on 1 row is :'  , arr[1,2]) 
print('last element is :', arr[1,3])
print("sum is :" , arr[1,2]+arr[1,3])

2 element on 1 row is : 6
last element is : 7
sum is : 13


In [29]:
 # access 3 -D arrays for indexing
                 #      0                 1        this is the  index position
                #  0,      1         0,         1  this is the this is the second index position 
                # 0,1,2   0,1,2     0,1,2    0 ,  1, 2   this is the  the element inside the index element 
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10.2,12,13]]])
print(arr[0,1,2])



6.0


In [31]:

# slicing of the numpy arrays 

arr = np.array ([1,2,3,4,5,6,7,8,9])
print(arr[1:5])
print(type(arr))

[2 3 4 5]
<class 'numpy.ndarray'>


In [32]:
# spiking the element

arr = np.array ([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[1 3 5 7 9]


In [33]:
# slicing in 2-d arrays

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [35]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,0:4])

[1 2 3 4]


In [37]:
 # checking the data type of the arrays

arr = np.array ([1,2,3,4,5,6,7,8,9])

print(arr.dtype)

int32


In [38]:
arr = np.array(['animals','python'])
print(arr.dtype)

<U7


In [39]:
 # creating a array with defined data type

arr = np.array([1,2,3,4] , dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [43]:
#create an arrays with data types of 4 bytes interger

arr = np.array([1,2,3,4] , dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [44]:
arr = np.array([1,2,3,4] , dtype = 'f4')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [45]:
#  numpy array shape
# the shape of array is the number of the emement in each dimenstion


#print the shape of the 2-d array


arr = np.array([[1,2,3,4],[5,6,7,8]])         
print(arr.shape)


(2, 4)


In [46]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])         
print(arr.shape)

(1, 3, 4)


In [48]:
  #  joining numpy arrays 

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
print(arr3)


[1 2 3 4 5 6]


In [49]:
# join 2-d arrys

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

np.concatenate((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

np.concatenate((arr1,arr2),axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [55]:
# splitting numpy arrays

# spliting the arrys in 3 parts

arr = np.array([1,2,3,4,5,6])
narr  = np.array_split(arr,3)
print(narr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [60]:
arr = np.array([1,2,3,4,5,6])
np.array_split(arr,3)


[array([1, 2]), array([3, 4]), array([5, 6])]

In [64]:
        # ravel and flatten  (do the same thing)
# convert multi dim  array into 1 d arrays


m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(m)
print('dimension is :' , m.ndim)

n = m.ravel()  # convert 3-d to 1-d
print(n)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is : 3
[1 2 3 4 5 6 7 8 9]


In [65]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(m)
print('dimension is :' , m.ndim)

n = m.flatten()  # convert 3-d to 1-d
print(n)
print('dimension is :' , n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is : 3
[1 2 3 4 5 6 7 8 9]
dimension is : 1


In [74]:
c = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(c)
print('how many dimension is :',c.ndim)

print('the new dim is :' , c.ravel())



[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
how many dimension is : 4
the new dim is : [1 2 3 4 5 6 7 8 9]


In [76]:
#  unique Function

arr = np.array([12,14,13,15,16,5,28,61,864,1,564,8,16,82,94,8,940,628,4,])
print(arr)
x = np.unique(arr)
print(x)

[ 12  14  13  15  16   5  28  61 864   1 564   8  16  82  94   8 940 628
   4]
[  1   4   5   8  12  13  14  15  16  28  61  82  94 564 628 864 940]


In [79]:
# find index position  (return function)

arr = np.array([12,14,13,15,16,5,28,61,864,1,564,8,16,82,94,8,940,628,4,])
print(arr)
x = np.unique(arr , return_index = True)
print(x)


[ 12  14  13  15  16   5  28  61 864   1 564   8  16  82  94   8 940 628
   4]
(array([  1,   4,   5,   8,  12,  13,  14,  15,  16,  28,  61,  82,  94,
       564, 628, 864, 940]), array([ 9, 18,  5, 11,  0,  2,  1,  3,  4,  6,  7, 13, 14, 10, 17,  8, 16],
      dtype=int64))


In [80]:
arr = np.array([12,14,13,15,16,5,28,61,864,1,564,8,16,82,94,8,940,628,4,])
print(arr)
x = np.unique(arr , return_index = True ,return_counts = True)
print(x)

[ 12  14  13  15  16   5  28  61 864   1 564   8  16  82  94   8 940 628
   4]
(array([  1,   4,   5,   8,  12,  13,  14,  15,  16,  28,  61,  82,  94,
       564, 628, 864, 940]), array([ 9, 18,  5, 11,  0,  2,  1,  3,  4,  6,  7, 13, 14, 10, 17,  8, 16],
      dtype=int64), array([1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))


In [81]:
#  delete function

a = np.array([1,23,25,68,47,58])
d = np.delete(a,[2])
print(d)

[ 1 23 68 47 58]


In [87]:

a = np.array([[1,23,25],[68,47,58],[48,89,99]])
print(a)
d = np.delete(a,1,axis = 0)
print()
print(d)

[[ 1 23 25]
 [68 47 58]
 [48 89 99]]

[[ 1 23 25]
 [48 89 99]]


In [88]:
a = np.array([[1,23,25],[68,47,58],[48,89,99]])
print(a)
d = np.delete(a,1,axis = 1)
print()
print(d)

[[ 1 23 25]
 [68 47 58]
 [48 89 99]]

[[ 1 25]
 [68 58]
 [48 99]]


In [89]:
a = np.array([[1,23,25],[68,47,58],[48,89,99]])
print(a)
d = np.delete(a,2,axis = 0)
print()
print(d)

[[ 1 23 25]
 [68 47 58]
 [48 89 99]]

[[ 1 23 25]
 [68 47 58]]


In [90]:
a = np.array([[1,23,25],[68,47,58],[48,89,99]])
print(a)
d = np.delete(a,2,axis = 1)
print()
print(d)

[[ 1 23 25]
 [68 47 58]
 [48 89 99]]

[[ 1 23]
 [68 47]
 [48 89]]
